name: Build Module

on:
  workflow_dispatch:
    inputs:
      major:
        type: number
        description: 'Major version increment by? (e.g. 1)'
        default: 0
        required: true
      minor:
        type: number
        description: 'Minor version increment by? (e.g. 1)'
        default: 1
        required: true

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: Yakov5776/gh-apkmirror-dl@v1.3
        with:
          org: 'google-inc'
          repo: 'youtube'
          version: '20.13.41'
          bundle: false
          filename: 'com.google.android.youtube.apk'

      - name: Move APK to module/base
        run: |
          mkdir  -p ./module/base/
          mv ./com.google.android.youtube.apk ./module/base/

      - name: Generate Patched Youtube APK
        run: |
          shopt -s nullglob
          patch_files=( *.rvp )
          rvx_cli=( *.jar )
          base_apk=( module/base/*.apk )
          
          if [ ${#patch_files[@]} -eq 0 ]; then
            echo "Error: No .rvp patch file found." >&2
            exit 1
          fi
          if [ ${#rvx_cli[@]} -eq 0 ]; then
            echo "Error: No .jar CLI file found." >&2
            exit 1
          fi
          if [ ${#base_apk[@]} -eq 0 ]; then
            echo "Error: No base APK found in /module/base/." >&2
            exit 1
          fi
          
          patch_file="${patch_files[0]}"
          cli_jar="${rvx_cli[0]}"
          apk_file="${base_apk[0]}"
          
          echo "Using patch file: $patch_file"
          echo "Using CLI JAR: $cli_jar"
          echo "Using base APK: $apk_file"
          echo "Signer: ${{ github.repository_owner }}"
          
          args=(
            # Hide ads
            --ei 172
            # Video ads
            --ei 173
            # Copy video URL
            --ei 174
            # Remove viewer discretion dialog
            --ei 175
            # Disable double tap actions
            --ei 176
            # Downloads
            --ei 177
            # Seekbar
            --ei 178
            # Swipe controls
            --ei 179
            # Disable auto captions
            --ei 180
            # Custom branding
            --ei 181
            # Change header
            --ei 182
            # Hide video action buttons
            --ei 183
            # Navigation buttons
            --ei 184
            # Hide player overlay buttons
            --ei 185
            # Change form factor
            --ei 186
            # Hide end screen cards
            --ei 187
            # Hide end screen suggested video
            --ei 188
            # Disable fullscreen ambient mode
            --ei 189
            # Hide layout components
            --ei 190
            # Hide info cards
            --ei 191
            # Hide player flyout menu items
            --ei 192
            # Hide related video overlay
            --ei 193
            # Disable rolling number animations
            --ei 194
            # Hide Shorts components
            --ei 195
            -OhideShortsAppShortcut=true
            -OhideShortsWidget=true
            # Disable sign in to TV popup
            --ei 196
            # Hide timestamp
            --ei 197
            # Miniplayer
            --ei 198
            # Disable player popup panels
            --ei 199
            # Exit fullscreen mode
            --ei 200
            # Open videos fullscreen
            --ei 201
            # Custom player overlay opacity
            --ei 202
            # Return YouTube Dislike
            --ei 203
            # Wide search bar
            --ei 204
            # Shorts autoplay
            --ei 205
            # Open Shorts in regular player
            --ei 206
            # SponsorBlock
            --ei 207
            # Spoof app version
            --ei 208
            # Change start page
            --ei 209
            # Disable resuming Shorts on startup
            --ei 210
            # Alternative thumbnails
            --ei 212
            # Bypass image region restrictions
            --ei 213
            # Announcements
            --di 214
            # Always repeat
            --ei 215
            # Remove background playback restrictions
            --ei 216
            # Enable debugging
            --di 217
            # Spoof device dimensions
            --ei 218
            # Check watch history domain name resolution
            --ei 219
            # GmsCore support
            --di 220
            # Disable haptic feedback
            --ei 221
            # Bypass URL redirects
            --ei 222
            # Open links externally
            --ei 223
            # Remove tracking query parameter
            --ei 224
            # Spoof video streams
            --ei 225
            # Force original audio
            --ei 226
            # Disable HDR video
            --ei 227
            # Video quality
            --ei 228
            # Playback speed
            --ei 229
            "$apk_file"
          )
          
          java -jar "$cli_jar" patch -p "$patch_file" --ei 211 -OdarkThemeBackgroundColor="@android:color/black" -o "com.google.android.youtube_amoled.apk" -t "./temp" --purge --signer "${{ github.repository_owner }}" "${args[@]}"
          java -jar "$cli_jar" patch -p "$patch_file" --ei 211 -OdarkThemeBackgroundColor="@android:color/system_neutral1_900" -OlightThemeBackgroundColor="@android:color/system_neutral1_50" -o "com.google.android.youtube_material.apk" -t "./temp" --purge --signer "${{ github.repository_owner }}" "${args[@]}"

      - name: Create amoled module zip
        run: |
          rm -rf module/apk
          mkdir -p module/apk
          cp com.google.android.youtube_amoled.apk module/apk/
          MODULE_NAME="Revanced-YT-amoled-For-SUSFS"
          zip -9 -r "$MODULE_NAME.zip" ./module/. -x "*.git*" -x ".github/*" -x "*.yml" -x "*apk.keystore*" -x "README.md"

      - name: Upload amoled Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Revanced-YT-amoled-For-SUSFS
          path: "module/*"

      - name: Create material module zip
        run: |
          rm -rf module/apk
          mkdir -p module/apk
          cp com.google.android.youtube_material.apk module/apk/
          MODULE_NAME="Revanced-material-YT-For-SUSFS"
          zip -9 -r "$MODULE_NAME.zip" ./module/. -x "*.git*" -x ".github/*" -x "*.yml" -x "*apk.keystore*" -x "README.md"

      - name: Upload material Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Revanced-material-YT-For-SUSFS
          path: "module/*"
