name: Build Module

on:
  workflow_dispatch:
    inputs:
      major:
        type: number
        description: 'Major version increment by? (e.g. 1)'
        default: 0
        required: true
      minor:
        type: number
        description: 'Minor version increment by? (e.g. 1)'
        default: 1
        required: true

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: Yakov5776/gh-apkmirror-dl@v1.3
        with:
          org: 'google-inc'
          repo: 'youtube'
          version: '20.13.41'
          bundle: false
          filename: 'com.google.android.youtube.apk'

      - name: Move APK to module/base
        run: |
          mkdir  -p ./module/base/
          mkdir  -p ./module/apk/
          mv ./com.google.android.youtube.apk ./module/base/

      - name: Generate Patched Youtube APK
        run: |
          shopt -s nullglob
          patch_files=( *.rvp )
          rvx_cli=( *.jar )
          base_apk=( module/base/*.apk )
          
          if [ ${#patch_files[@]} -eq 0 ]; then
            echo "Error: No .rvp patch file found." >&2
            exit 1
          fi
          if [ ${#rvx_cli[@]} -eq 0 ]; then
            echo "Error: No .jar CLI file found." >&2
            exit 1
          fi
          if [ ${#base_apk[@]} -eq 0 ]; then
            echo "Error: No base APK found in /module/base/." >&2
            exit 1
          fi
          
          patch_file="${patch_files[0]}"
          cli_jar="${rvx_cli[0]}"
          apk_file="${base_apk[0]}"
          
          echo "Using patch file: $patch_file"
          echo "Using CLI JAR: $cli_jar"
          echo "Using base APK: $apk_file"
          echo "Signer: ${{ github.repository_owner }}"
          java -jar "$cli_jar" patch -p "$patch_file" -o "./module/apk" -t "./temp" --purge --signer "${{ github.repository_owner }}" \
          # Hide ads
          --ei 172 \
          # Video ads
          --ei 173 \
          # Copy video URL
          --ei 174 \
          # Remove viewer discretion dialog
          --ei 175 \
          # Disable double tap actions
          --ei 176 \
          # Downloads
          --ei 177 \
          # Seekbar
          --ei 178 \
          # Swipe controls
          --ei 179 \
          # Disable auto captions
          --ei 180 \
          # Custom branding
          --ei 181 \
          # Change header
          --ei 182 \
          # Hide video action buttons
          --ei 183 \
          # Navigation buttons
          --ei 184 \
          # Hide player overlay buttons
          --ei 185 \
          # Change form factor
          --ei 186 \
          # Hide end screen cards
          --ei 187 \
          # Hide end screen suggested video
          --ei 188 \
          # Disable fullscreen ambient mode
          --ei 189 \
          # Hide layout components
          --ei 190 \
          "$apk_file"

      - name: Create module zip
        working-directory: ./module
        run: |
          MODULE_NAME="Revanced-YT-For-SUSFS"
          zip -r "../$MODULE_NAME.zip" . -x "*.git*" -x ".github/*" -x "*.yml" -x "*apk.keystore*" -x "README.md"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: module-zip
          path: "*.zip"